#!/bin/bash
# Create a Moodle site on a CentOS server running Apache and MySQL/MariaDB.
# PHP and MySQL/MariaDB must be alread installed and configured.
# Leon Stringer <leon@priorsvle.com>
local_repo=/usr/share/repos/moodle
branch=MOODLE_37_STABLE
upstream_repo=git://git.moodle.org/moodle.git
tag=""
verbose=0
OPTIND=1

function show_help () {
	echo "Usage: new_test_site [[-b branch_ver] | [-t tag]] [-g git_repo] domain-name"
	echo
	echo " -b branch_ver Optional major Moodle version, e.g. 35 for Moodle 3.5."
	echo "               If not specified $branch is used.  Minimum: 25 (for"
	echo "               Moodle 2.5).  Cannot be used with -t."
	echo
	echo " -t tag        Optional Moodle minor version, e.g. v3.5.1  Cannot be"
	echo "               used with -b."
	echo
	echo " -g git_repo   Optional upstream Git repository to use.  By default"
	echo "               $upstream_repo is used.  If the source code"
	echo "               directory is present this is used, avoiding Git clone."
	echo
	echo " -v            Verbose output."
	echo
	echo "Examples:"
	echo "    new_test_site moodle1.example.com"
	echo
	echo "    new_test_site -b 35 -g https://github.com/moodle/moodle.git \\"
	echo "    moodle2.example.com"
	echo
	echo "    new_test_site -t v3.6.2 moodle3.example.com"
	echo
}

function log () {
    if [ "$verbose" -eq "1" ]; then
        echo "$@"
    fi
}

while getopts "g:b:t:h?v" opt; do
	case "$opt" in
		b) branch=MOODLE_${OPTARG}_STABLE
			;;
		g) upstream_repo=$OPTARG
			;;
		t) tag=$OPTARG
			branch=MOODLE_${tag:1:1}${tag:3:1}_STABLE
			;;
		h|\?) show_help
			exit 0
			;;
		v) verbose=1
			;;
	esac
done

shift $((OPTIND-1))

if [ "$#" -ne 1 ]; then
	>&2 echo "Error: Missing domain name."
	exit 1
fi

apache_conf_dir=/etc/httpd/conf.d
cert_dir=/etc/pki/tls/certs
key_dir=/etc/pki/tls/private
www_user=apache
www_service=httpd
key_file_mode=600
key_owner_g=root
os_id=`grep -h "^ID=" /etc/*-release | cut -d'=' -f 2`

if [ "$os_id" == "debian" ]; then
	log "Using file system locations for Debian."
	apache_conf_dir=/etc/apache2/sites-enabled
	cert_dir=/etc/ssl/certs
	key_dir=/etc/ssl/private
	www_user=www-data
	www_service=apache2
	key_file_mode=640
	key_owner_g=ssl-cert
else
	log "Using file system locations for CentOS/RHEL/Fedora."
fi

domain_name=$1
conf_file=$apache_conf_dir/$domain_name.conf
cert_file=$cert_dir/$domain_name.crt
key_file=$key_dir/$domain_name.key
sitedir=/var/www/$domain_name
moodle=$sitedir/moodle
dataroot=$sitedir/moodledata
dbname=${domain_name//./_}
dbpass=`openssl rand -base64 12`	# https://unix.stackexchange.com/a/306107

lang=${LANG:0:2}
log "Language detected: $lang"

if [ -e "$conf_file" ]; then
	>&2 echo "Error: $conf_file already exists."
	exit 1
fi

if [ -e "$cert_file" ]; then
	>&2 echo "Error: $cert_file already exists."
	exit 1
fi

if [ -e "$key_file" ]; then
	>&2 echo "Error: $key_file already exists."
	exit 1
fi

log "Creating https://$domain_name"

mysql -u root -p --execute="CREATE DATABASE \`$dbname\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;CREATE USER '$dbname'@'localhost' IDENTIFIED BY '$dbpass';GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON \`$dbname\`.* TO '$dbname'@'localhost'"

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Unable to create database or database user."
	exit 1
fi

if [ -d "$sitedir" ]; then
	mkdir $dataroot
else
	mkdir $sitedir $dataroot
fi

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Unable to create directories."
	exit 1
fi

chown $www_user. $dataroot
selinux_status=`getenforce 2> /dev/null`

if [ "$?" -eq "0" ] && [ "$selinux_status" == "Enforcing" ]; then
	semanage fcontext -a -t httpd_sys_rw_content_t "$dataroot"
	restorecon -v "$dataroot" > /dev/null
fi

 # If there's a moodle dir, assume this is a source code dir.  If this is an
 # existing site the config.php will stop install.php (and if there's an
 # existing database with the same name then the CREATE DATABASE would have
 # failed previously).
if [ ! -d "$moodle" ]; then
	git_clone_args=("-q")

	 # Is there a local Git repo for Moodle?
	if [ -d "$local_repo" ]; then
		git_clone_args+=("--reference" "$local_repo")
	fi

	git_clone_args+=("$upstream_repo")

	if [ ! -z "$tag" ]; then
		git_clone_args+=("--branch" $tag)
	else
		git_clone_args+=("--branch" $branch)
	fi

	git_clone_args+=("$moodle")
	git clone ${git_clone_args[@]}
fi

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Git clone failed."
	exit 1
fi

install_args=("--wwwroot=https://$domain_name" "--dbname=$dbname" "--dbuser=$dbname" "--dbpass=$dbpass" "--fullname=Test Site" "--shortname=Home" "--adminpass=Password-1" "--agree-license" "--non-interactive" "--lang=$lang")

 # dbtype mariadb introduced with Moodle 2.6
if [ "$branch" == "MOODLE_25_STABLE" ]; then
	install_args+=("--dbtype=mysqli")
else
	install_args+=("--dbtype=mariadb")
fi

if [ "$branch" != "MOODLE_25_STABLE" ] && [ "$branch" != "MOODLE_26_STABLE" ] \
				&& [ "$branch" != "MOODLE_27_STABLE" ]; then
	install_args+=("--adminemail=admin@example.com")
fi

php -f $sitedir/moodle/admin/cli/install.php -- "${install_args[@]}" > /dev/null

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Install command failed."
	exit 1
fi

chown $www_user $sitedir/moodle/config.php

openssl req -x509 -newkey rsa:4096 -keyout $key_file -out $cert_file -days 720 -nodes -subj "/C=GB/O=PriorsVLE Ltd/CN=$domain_name" > /dev/null

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Unable to create self-signed certificates."
	exit 1
fi

chmod $key_file_mode $key_file
chown root:$key_owner_g $key_file

echo "<VirtualHost *:443>" > $conf_file

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Unable to create Apache config file."
	exit 1
fi

echo "    ServerName $domain_name" >> $conf_file
echo "    DocumentRoot $sitedir/moodle" >> $conf_file
echo "    SSLEngine on" >> $conf_file
echo "    SSLCertificateFile $cert_file" >> $conf_file
echo "    SSLCertificateKeyFile $key_file" >> $conf_file
echo "</VirtualHost>" >> $conf_file

apachectl configtest > /dev/null 2>&1

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Apache configuration error."
	exit 1
fi

systemctl reload $www_service

if [ "$?" -ne "0" ]; then
	>&2 echo "Error: Error reloading Apache."
	exit 1
fi

log "Completed successfully."
